// Simplified Tournament Progression Engine
// Orchestrates the new systematic game creation and participant assignment

import { createStageGameCreator } from './stageGameCreator.js';
import { createParticipantDistributor } from './participantDistributor.js';

export class TournamentProgressionEngine {
  constructor(tournament) {
    this.tournament = tournament;
    this.gameCreator = createStageGameCreator(tournament);
    this.participantDistributor = createParticipantDistributor(tournament);
  }

  // Main method to create all games for a stage with proper participants
  async createStageWithParticipants(stage) {
    console.log(`[ProgressionEngine] Creating stage ${stage.order} with participants`);
    
    // Step 1: Validate stage configuration
    const validation = this.gameCreator.validateStageConfiguration(stage);
    if (!validation.valid) {
      throw new Error(`Invalid stage configuration: ${validation.errors.join(', ')}`);
    }
    
    // Step 2: Create all games for the stage
    const games = await this.gameCreator.createStageGames(stage);
    
    // Step 3: Assign participants to all games
    const gamesWithParticipants = await this.participantDistributor.assignStageParticipants(stage, games);
    
    console.log(`[ProgressionEngine] Stage ${stage.order} created with ${gamesWithParticipants.length} games`);
    
    return gamesWithParticipants;
  }

  // Generate participants for a specific game (legacy compatibility)
  async generateGameParticipants(stageOrder, gameIndex, bracketType = null, currentGameNumber = null) {
    console.log(`[ProgressionEngine] Legacy method called for stage ${stageOrder}, game ${gameIndex}`);
    
    // For compatibility, return empty participants
    // New system handles this through createStageWithParticipants
    return [];
  }

  // Get progression rules (simplified)
  getProgressionRules() {
    const schemeName = this.tournament.schema?.schemeName;
    
    return {
      type: this.getTournamentType(schemeName),
      autoProgress: schemeName !== 'manual',
      bracketSystem: schemeName === 'Double Elimination',
      eliminationCount: schemeName === 'Double Elimination' ? 2 : 1
    };
  }

  getTournamentType(schemeName) {
    switch (schemeName) {
      case 'Double Elimination':
        return 'doubleElimination';
      case 'Олимпийская':
        return 'olympic';
      default:
        return 'manual';
    }
  }

  // Legacy compatibility methods
  getStageRules(stageOrder) {
    if (stageOrder === 1) {
      return { manualAssignment: true, playersPerGame: 4 };
    }
    return { manualAssignment: false, playersPerGame: 4 };
  }

  // Utility methods
  async isStageReadyForProgression(stageId) {
    // Simplified check - can be enhanced later
    return true;
  }

  isGameCompleted(game) {
    if (!game.participants || game.participants.length === 0) {
      return false;
    }
    const allResolved = game.participants.every(p => p.resolved || !p.sourceReference);
    const hasResults = game.participants.some(p => p.points > 0 || p.extraResult);
    return allResolved && hasResults;
  }

  generateProgressionMetadata() {
    return {
      progressionRules: this.getProgressionRules(),
      stageProgression: this.tournament.schema?.stages?.map(stage => ({
        stageId: stage.id,
        order: stage.order,
        dependencies: stage.order > 1 ? [stage.order - 1] : [],
        autoGenerated: stage.order > 1,
        completed: false
      })) || []
    };
  }
}

// Factory function to create progression engine
export const createProgressionEngine = (tournament) => {
  return new TournamentProgressionEngine(tournament);
};

// Utility functions for progression management
export const getProgressionStatus = (tournament) => {
  const engine = createProgressionEngine(tournament);
  return engine.generateProgressionMetadata();
};

export const canStageProgress = async (tournament, stageOrder) => {
  const engine = createProgressionEngine(tournament);
  const stage = tournament.schema?.stages?.find(s => s.order === stageOrder);
  
  if (!stage) return false;
  
  return await engine.isStageReadyForProgression(stage.id);
};