// Generates setup.sql (schema + seed) from local JSON files
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function readJson(rel) {
  try { return JSON.parse(readFileSync(join(root, rel), 'utf-8')); }
  catch { return []; }
}

// Escape a JS value as a PostgreSQL literal
function lit(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

const schema = readFileSync(join(root, 'schema.sql'), 'utf-8');
const tournaments = readJson('src/app/api/tournaments/db.json');
const games       = readJson('src/app/api/games/db.json');
const players     = readJson('src/app/api/players/db.json');
const users       = readJson('src/app/api/users/db.json');

const lines = [
  '-- Generated by scripts/generate-sql.js',
  '-- Run this entire file in the Supabase SQL editor',
  '',
  '-- SCHEMA ----------------------------------------------------------------',
  schema,
  '',
  '-- SEED DATA -------------------------------------------------------------',
  '',
  '-- Players',
];

for (const p of players) {
  lines.push(
    `INSERT INTO players (id, player_type, first_name, last_name, name) VALUES ` +
    `(${lit(p.id)}, ${lit(p.playerType)}, ${lit(p.firstName ?? null)}, ${lit(p.lastName ?? null)}, ${lit(p.name ?? null)}) ` +
    `ON CONFLICT (id) DO NOTHING;`
  );
}

lines.push('', '-- Users');
for (const u of users) {
  lines.push(
    `INSERT INTO users (id, name, email, role, color) VALUES ` +
    `(${lit(u.id)}, ${lit(u.name)}, ${lit(u.email ?? null)}, ${lit(u.role ?? null)}, ${lit(u.color ?? null)}) ` +
    `ON CONFLICT (id) DO NOTHING;`
  );
}
if (users.length > 0) {
  const maxId = Math.max(...users.map(u => u.id));
  lines.push(`SELECT setval('users_id_seq', ${maxId});`);
}

lines.push('', '-- Tournaments');
for (const t of tournaments) {
  lines.push(
    `INSERT INTO tournaments (id, name, start_date, end_date, type, game_creation_method, schema, participants, results) VALUES ` +
    `(${lit(t.id)}, ${lit(t.name)}, ${lit(t.startDate ?? null)}, ${lit(t.endDate ?? null)}, ` +
    `${lit(t.type ?? null)}, ${lit(t.gameCreationMethod ?? null)}, ` +
    `${lit(t.schema ?? {})}, ${lit(t.participants ?? [])}, ${lit(t.results ?? [])}) ` +
    `ON CONFLICT (id) DO NOTHING;`
  );
}
if (tournaments.length > 0) {
  const maxId = Math.max(...tournaments.map(t => t.id));
  lines.push(`SELECT setval('tournaments_id_seq', ${maxId});`);
}

lines.push('', '-- Games');
for (const g of games) {
  lines.push(
    `INSERT INTO games (id, game_number, tournament_id, stage_id, game_date, game_place, presenter_id, ` +
    `tournament_type, game_letter, bracket_type, bracket_position, stage_order, ` +
    `stage_themes, status, completed, completed_at, finished_at, last_updated, ` +
    `participants, game_state, completed_themes) VALUES ` +
    `(${lit(g.id)}, ${lit(g.gameNumber ?? null)}, ${lit(g.tournamentId)}, ${lit(g.stageId)}, ` +
    `${lit(g.gameDate ?? null)}, ${lit(g.gamePlace ?? null)}, ${lit(g.presenterId ?? null)}, ` +
    `${lit(g.tournamentType ?? null)}, ${lit(g.gameLetter ?? null)}, ${lit(g.bracketType ?? null)}, ` +
    `${lit(g.bracketPosition ?? null)}, ${lit(g.stageOrder ?? null)}, ` +
    `${lit(g.stageThemes ?? [])}, ${lit(g.status ?? 'pending')}, ${lit(g.completed ?? false)}, ` +
    `${lit(g.completedAt ?? null)}, ${lit(g.finishedAt ?? null)}, ${lit(g.lastUpdated ?? null)}, ` +
    `${lit(g.participants ?? [])}, ${lit(g.gameState ?? {})}, ` +
    `${g.completedThemes != null ? lit(g.completedThemes) : 'NULL'}) ` +
    `ON CONFLICT (id) DO NOTHING;`
  );
}
if (games.length > 0) {
  const maxId = Math.max(...games.map(g => g.id));
  lines.push(`SELECT setval('games_id_seq', ${maxId});`);
}

const sql = lines.join('\n');
const outPath = join(root, 'setup.sql');
writeFileSync(outPath, sql, 'utf-8');
console.log(`Written ${outPath} (${(sql.length / 1024).toFixed(1)} KB, ${games.length} games, ${tournaments.length} tournaments, ${players.length} players, ${users.length} users)`);
